name: Cron

on:
  push:
    branches:
      - main
    paths:
      - "legacy/cron.yaml"
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      id-token: "write" # TODO: separate build and deploy jobs and create reusable deploy workflow
    runs-on: ubuntu-22.04
    steps:
      - name: 🛫 Checkout
        uses: actions/checkout@v5

      - name: ☁️ Setup GCloud
        uses: codeforlife-education/codeforlife-workspace/.github/actions/gcloud/setup@main

      - name: 🚀 Deploy CRON Jobs on GCloud
        run: gcloud app deploy legacy/cron.yaml
